import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SideNav from "@/components/SideNav";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

const PageLayout: React.FC<{
  title?: string;
  children: any;
  noHeader?: boolean;
}> = ({ title, children, noHeader }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SideNav />
        <div className={styles.container}>
          {!noHeader && <Header />}
          <div className={styles.body}>{children}</div>
        </div>
      </main>
    </>
  );
};

export default PageLayout;
